Video là sự kết hợp của nhiều ảnh theo thời gian. Ảnh là không gian (Spatial) còn Video thì theo thời gian (Temporal)
Dò vết đối tượng bằng Meanshift tracking là một trong rất nhiều kỹ thật dò vết đối tượng trong video! Các bước thực hiện như sau:
1. Xây dựng phân bố dữ liệu (Mô hình hoá dữ liệu về màu sắc, về vị trí, mật độ, mỗi dữ liệu thành 1 điểm trên đồ thị, tạo thành 1 đám mây điểm, mỗi điểm là một phân bố của dữ liệu)
2. Chọn ngẫu nhiên 1 vùng của phân bố
3. Tìm điểm trung tâm (Centroid) của vùng đó
4. Lấy Centroid của vùng cũ làm tâm điểm để tạo 1 vùng mới
5. Lặp lại bước 3 và 4 cho đến khi hội tụ (Centroid không di chuyển nữa)

Bản chất toán học
- Xét tập $S$ gồm $n$ điểm dữ liệu $x_i$
- Trong đó $x$: là điểm trung tâm (Mean/Centroid) của vùng hiện tại
- Gọi $K(x)$ là kernel function (Xác định mức độ ảnh hưởng của từng data point đến việc tìm centroid/mean)
- gọi $m(x)$ là mean/centroid của vùng mới với $x$ làm tâm thì có công thức tính như sau:

$$m(x)=\frac{\sum_{i=1}^n K(x-x_i) x_i}{\sum_{i=1}^n K(x-x_i)}$$
- $m(x) - x$ gọi là meanshift
- Dừng khi $m(x) = x$

Người ta có thể dùg Color Histogram hay Different scales để xác định vật thể 

Viêc dò vết đối tượng bằng hàm $K(x-x_i)$ có nhiều cách khác nhau



In [7]:
from matplotlib import pyplot as plt
import cv2
import numpy as np


def Show(image, name, gray=False):
    if gray:
        plt.imshow(image, cmap='gray')
    else:
        plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.title(name)


image = cv2.imread('image\icon.png', cv2.IMREAD_COLOR)
(w, h, c) = image.shape
dst = image[160:250, 130:250]
plt.subplot(121), Show(image, "Input")
plt.subplot(122), Show(dst, "Crop")
plt.show()


[[0.36787944 0.60653066 0.36787944]
 [0.60653066 1.         0.60653066]
 [0.36787944 0.60653066 0.36787944]]
